version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: "postgresql"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgresql:/data/postgres
    env_file:
      - ./postgres.env
    restart: always

  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis:/data
    restart: always

  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo:/data/db
    restart: always
